/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainLayoutImport } from './routes/_mainLayout'
import { Route as AuthLayoutImport } from './routes/_authLayout'
import { Route as MainLayoutIndexImport } from './routes/_mainLayout/index'
import { Route as AuthLayoutRegisterImport } from './routes/_authLayout/register'
import { Route as AuthLayoutLoginImport } from './routes/_authLayout/login'
import { Route as MainLayoutRoomDashboardIndexImport } from './routes/_mainLayout/room-dashboard/index'
import { Route as MainLayoutProfileIndexImport } from './routes/_mainLayout/profile/index'
import { Route as MainLayoutInspectionsIndexImport } from './routes/_mainLayout/inspections/index'
import { Route as MainLayoutEventsIndexImport } from './routes/_mainLayout/events/index'
import { Route as MainLayoutAdminIndexImport } from './routes/_mainLayout/admin/index'
import { Route as MainLayoutInspectionsCreateImport } from './routes/_mainLayout/inspections/create'
import { Route as MainLayoutEventsCreateImport } from './routes/_mainLayout/events/create'
import { Route as MainLayoutRoomsRoomIdIndexImport } from './routes/_mainLayout/rooms/$roomId.index'
import { Route as MainLayoutProfileProfileIdIndexImport } from './routes/_mainLayout/profile/$profileId.index'
import { Route as MainLayoutInspectionsInspectionIdIndexImport } from './routes/_mainLayout/inspections/$inspectionId.index'
import { Route as MainLayoutEventsEventIdIndexImport } from './routes/_mainLayout/events/$eventId.index'
import { Route as MainLayoutRoomsRoomIdEditImport } from './routes/_mainLayout/rooms/$roomId.edit'
import { Route as MainLayoutEventsEventIdInviteImport } from './routes/_mainLayout/events/$eventId.invite'
import { Route as MainLayoutEventsEventIdEditImport } from './routes/_mainLayout/events/$eventId.edit'

// Create/Update Routes

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutIndexRoute = MainLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const AuthLayoutRegisterRoute = AuthLayoutRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const MainLayoutRoomDashboardIndexRoute =
  MainLayoutRoomDashboardIndexImport.update({
    id: '/room-dashboard/',
    path: '/room-dashboard/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutProfileIndexRoute = MainLayoutProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutInspectionsIndexRoute = MainLayoutInspectionsIndexImport.update(
  {
    id: '/inspections/',
    path: '/inspections/',
    getParentRoute: () => MainLayoutRoute,
  } as any,
)

const MainLayoutEventsIndexRoute = MainLayoutEventsIndexImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutAdminIndexRoute = MainLayoutAdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutInspectionsCreateRoute =
  MainLayoutInspectionsCreateImport.update({
    id: '/inspections/create',
    path: '/inspections/create',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutEventsCreateRoute = MainLayoutEventsCreateImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutRoomsRoomIdIndexRoute = MainLayoutRoomsRoomIdIndexImport.update(
  {
    id: '/rooms/$roomId/',
    path: '/rooms/$roomId/',
    getParentRoute: () => MainLayoutRoute,
  } as any,
)

const MainLayoutProfileProfileIdIndexRoute =
  MainLayoutProfileProfileIdIndexImport.update({
    id: '/profile/$profileId/',
    path: '/profile/$profileId/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutInspectionsInspectionIdIndexRoute =
  MainLayoutInspectionsInspectionIdIndexImport.update({
    id: '/inspections/$inspectionId/',
    path: '/inspections/$inspectionId/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutEventsEventIdIndexRoute =
  MainLayoutEventsEventIdIndexImport.update({
    id: '/events/$eventId/',
    path: '/events/$eventId/',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutRoomsRoomIdEditRoute = MainLayoutRoomsRoomIdEditImport.update({
  id: '/rooms/$roomId/edit',
  path: '/rooms/$roomId/edit',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutEventsEventIdInviteRoute =
  MainLayoutEventsEventIdInviteImport.update({
    id: '/events/$eventId/invite',
    path: '/events/$eventId/invite',
    getParentRoute: () => MainLayoutRoute,
  } as any)

const MainLayoutEventsEventIdEditRoute =
  MainLayoutEventsEventIdEditImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => MainLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_authLayout/register': {
      id: '/_authLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthLayoutRegisterImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/events/create': {
      id: '/_mainLayout/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof MainLayoutEventsCreateImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/inspections/create': {
      id: '/_mainLayout/inspections/create'
      path: '/inspections/create'
      fullPath: '/inspections/create'
      preLoaderRoute: typeof MainLayoutInspectionsCreateImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/admin/': {
      id: '/_mainLayout/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof MainLayoutAdminIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/events/': {
      id: '/_mainLayout/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof MainLayoutEventsIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/inspections/': {
      id: '/_mainLayout/inspections/'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof MainLayoutInspectionsIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/profile/': {
      id: '/_mainLayout/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainLayoutProfileIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/room-dashboard/': {
      id: '/_mainLayout/room-dashboard/'
      path: '/room-dashboard'
      fullPath: '/room-dashboard'
      preLoaderRoute: typeof MainLayoutRoomDashboardIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/events/$eventId/edit': {
      id: '/_mainLayout/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof MainLayoutEventsEventIdEditImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/events/$eventId/invite': {
      id: '/_mainLayout/events/$eventId/invite'
      path: '/events/$eventId/invite'
      fullPath: '/events/$eventId/invite'
      preLoaderRoute: typeof MainLayoutEventsEventIdInviteImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/rooms/$roomId/edit': {
      id: '/_mainLayout/rooms/$roomId/edit'
      path: '/rooms/$roomId/edit'
      fullPath: '/rooms/$roomId/edit'
      preLoaderRoute: typeof MainLayoutRoomsRoomIdEditImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/events/$eventId/': {
      id: '/_mainLayout/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof MainLayoutEventsEventIdIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/inspections/$inspectionId/': {
      id: '/_mainLayout/inspections/$inspectionId/'
      path: '/inspections/$inspectionId'
      fullPath: '/inspections/$inspectionId'
      preLoaderRoute: typeof MainLayoutInspectionsInspectionIdIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/profile/$profileId/': {
      id: '/_mainLayout/profile/$profileId/'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof MainLayoutProfileProfileIdIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/rooms/$roomId/': {
      id: '/_mainLayout/rooms/$roomId/'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof MainLayoutRoomsRoomIdIndexImport
      parentRoute: typeof MainLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutRegisterRoute: typeof AuthLayoutRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutRegisterRoute: AuthLayoutRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface MainLayoutRouteChildren {
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutEventsCreateRoute: typeof MainLayoutEventsCreateRoute
  MainLayoutInspectionsCreateRoute: typeof MainLayoutInspectionsCreateRoute
  MainLayoutAdminIndexRoute: typeof MainLayoutAdminIndexRoute
  MainLayoutEventsIndexRoute: typeof MainLayoutEventsIndexRoute
  MainLayoutInspectionsIndexRoute: typeof MainLayoutInspectionsIndexRoute
  MainLayoutProfileIndexRoute: typeof MainLayoutProfileIndexRoute
  MainLayoutRoomDashboardIndexRoute: typeof MainLayoutRoomDashboardIndexRoute
  MainLayoutEventsEventIdEditRoute: typeof MainLayoutEventsEventIdEditRoute
  MainLayoutEventsEventIdInviteRoute: typeof MainLayoutEventsEventIdInviteRoute
  MainLayoutRoomsRoomIdEditRoute: typeof MainLayoutRoomsRoomIdEditRoute
  MainLayoutEventsEventIdIndexRoute: typeof MainLayoutEventsEventIdIndexRoute
  MainLayoutInspectionsInspectionIdIndexRoute: typeof MainLayoutInspectionsInspectionIdIndexRoute
  MainLayoutProfileProfileIdIndexRoute: typeof MainLayoutProfileProfileIdIndexRoute
  MainLayoutRoomsRoomIdIndexRoute: typeof MainLayoutRoomsRoomIdIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutEventsCreateRoute: MainLayoutEventsCreateRoute,
  MainLayoutInspectionsCreateRoute: MainLayoutInspectionsCreateRoute,
  MainLayoutAdminIndexRoute: MainLayoutAdminIndexRoute,
  MainLayoutEventsIndexRoute: MainLayoutEventsIndexRoute,
  MainLayoutInspectionsIndexRoute: MainLayoutInspectionsIndexRoute,
  MainLayoutProfileIndexRoute: MainLayoutProfileIndexRoute,
  MainLayoutRoomDashboardIndexRoute: MainLayoutRoomDashboardIndexRoute,
  MainLayoutEventsEventIdEditRoute: MainLayoutEventsEventIdEditRoute,
  MainLayoutEventsEventIdInviteRoute: MainLayoutEventsEventIdInviteRoute,
  MainLayoutRoomsRoomIdEditRoute: MainLayoutRoomsRoomIdEditRoute,
  MainLayoutEventsEventIdIndexRoute: MainLayoutEventsEventIdIndexRoute,
  MainLayoutInspectionsInspectionIdIndexRoute:
    MainLayoutInspectionsInspectionIdIndexRoute,
  MainLayoutProfileProfileIdIndexRoute: MainLayoutProfileProfileIdIndexRoute,
  MainLayoutRoomsRoomIdIndexRoute: MainLayoutRoomsRoomIdIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof MainLayoutRouteWithChildren
  '/login': typeof AuthLayoutLoginRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/': typeof MainLayoutIndexRoute
  '/events/create': typeof MainLayoutEventsCreateRoute
  '/inspections/create': typeof MainLayoutInspectionsCreateRoute
  '/admin': typeof MainLayoutAdminIndexRoute
  '/events': typeof MainLayoutEventsIndexRoute
  '/inspections': typeof MainLayoutInspectionsIndexRoute
  '/profile': typeof MainLayoutProfileIndexRoute
  '/room-dashboard': typeof MainLayoutRoomDashboardIndexRoute
  '/events/$eventId/edit': typeof MainLayoutEventsEventIdEditRoute
  '/events/$eventId/invite': typeof MainLayoutEventsEventIdInviteRoute
  '/rooms/$roomId/edit': typeof MainLayoutRoomsRoomIdEditRoute
  '/events/$eventId': typeof MainLayoutEventsEventIdIndexRoute
  '/inspections/$inspectionId': typeof MainLayoutInspectionsInspectionIdIndexRoute
  '/profile/$profileId': typeof MainLayoutProfileProfileIdIndexRoute
  '/rooms/$roomId': typeof MainLayoutRoomsRoomIdIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthLayoutRouteWithChildren
  '/login': typeof AuthLayoutLoginRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/': typeof MainLayoutIndexRoute
  '/events/create': typeof MainLayoutEventsCreateRoute
  '/inspections/create': typeof MainLayoutInspectionsCreateRoute
  '/admin': typeof MainLayoutAdminIndexRoute
  '/events': typeof MainLayoutEventsIndexRoute
  '/inspections': typeof MainLayoutInspectionsIndexRoute
  '/profile': typeof MainLayoutProfileIndexRoute
  '/room-dashboard': typeof MainLayoutRoomDashboardIndexRoute
  '/events/$eventId/edit': typeof MainLayoutEventsEventIdEditRoute
  '/events/$eventId/invite': typeof MainLayoutEventsEventIdInviteRoute
  '/rooms/$roomId/edit': typeof MainLayoutRoomsRoomIdEditRoute
  '/events/$eventId': typeof MainLayoutEventsEventIdIndexRoute
  '/inspections/$inspectionId': typeof MainLayoutInspectionsInspectionIdIndexRoute
  '/profile/$profileId': typeof MainLayoutProfileProfileIdIndexRoute
  '/rooms/$roomId': typeof MainLayoutRoomsRoomIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/_authLayout/login': typeof AuthLayoutLoginRoute
  '/_authLayout/register': typeof AuthLayoutRegisterRoute
  '/_mainLayout/': typeof MainLayoutIndexRoute
  '/_mainLayout/events/create': typeof MainLayoutEventsCreateRoute
  '/_mainLayout/inspections/create': typeof MainLayoutInspectionsCreateRoute
  '/_mainLayout/admin/': typeof MainLayoutAdminIndexRoute
  '/_mainLayout/events/': typeof MainLayoutEventsIndexRoute
  '/_mainLayout/inspections/': typeof MainLayoutInspectionsIndexRoute
  '/_mainLayout/profile/': typeof MainLayoutProfileIndexRoute
  '/_mainLayout/room-dashboard/': typeof MainLayoutRoomDashboardIndexRoute
  '/_mainLayout/events/$eventId/edit': typeof MainLayoutEventsEventIdEditRoute
  '/_mainLayout/events/$eventId/invite': typeof MainLayoutEventsEventIdInviteRoute
  '/_mainLayout/rooms/$roomId/edit': typeof MainLayoutRoomsRoomIdEditRoute
  '/_mainLayout/events/$eventId/': typeof MainLayoutEventsEventIdIndexRoute
  '/_mainLayout/inspections/$inspectionId/': typeof MainLayoutInspectionsInspectionIdIndexRoute
  '/_mainLayout/profile/$profileId/': typeof MainLayoutProfileProfileIdIndexRoute
  '/_mainLayout/rooms/$roomId/': typeof MainLayoutRoomsRoomIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/'
    | '/events/create'
    | '/inspections/create'
    | '/admin'
    | '/events'
    | '/inspections'
    | '/profile'
    | '/room-dashboard'
    | '/events/$eventId/edit'
    | '/events/$eventId/invite'
    | '/rooms/$roomId/edit'
    | '/events/$eventId'
    | '/inspections/$inspectionId'
    | '/profile/$profileId'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/register'
    | '/'
    | '/events/create'
    | '/inspections/create'
    | '/admin'
    | '/events'
    | '/inspections'
    | '/profile'
    | '/room-dashboard'
    | '/events/$eventId/edit'
    | '/events/$eventId/invite'
    | '/rooms/$roomId/edit'
    | '/events/$eventId'
    | '/inspections/$inspectionId'
    | '/profile/$profileId'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_mainLayout'
    | '/_authLayout/login'
    | '/_authLayout/register'
    | '/_mainLayout/'
    | '/_mainLayout/events/create'
    | '/_mainLayout/inspections/create'
    | '/_mainLayout/admin/'
    | '/_mainLayout/events/'
    | '/_mainLayout/inspections/'
    | '/_mainLayout/profile/'
    | '/_mainLayout/room-dashboard/'
    | '/_mainLayout/events/$eventId/edit'
    | '/_mainLayout/events/$eventId/invite'
    | '/_mainLayout/rooms/$roomId/edit'
    | '/_mainLayout/events/$eventId/'
    | '/_mainLayout/inspections/$inspectionId/'
    | '/_mainLayout/profile/$profileId/'
    | '/_mainLayout/rooms/$roomId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  MainLayoutRoute: MainLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authLayout",
        "/_mainLayout"
      ]
    },
    "/_authLayout": {
      "filePath": "_authLayout.tsx",
      "children": [
        "/_authLayout/login",
        "/_authLayout/register"
      ]
    },
    "/_mainLayout": {
      "filePath": "_mainLayout.tsx",
      "children": [
        "/_mainLayout/",
        "/_mainLayout/events/create",
        "/_mainLayout/inspections/create",
        "/_mainLayout/admin/",
        "/_mainLayout/events/",
        "/_mainLayout/inspections/",
        "/_mainLayout/profile/",
        "/_mainLayout/room-dashboard/",
        "/_mainLayout/events/$eventId/edit",
        "/_mainLayout/events/$eventId/invite",
        "/_mainLayout/rooms/$roomId/edit",
        "/_mainLayout/events/$eventId/",
        "/_mainLayout/inspections/$inspectionId/",
        "/_mainLayout/profile/$profileId/",
        "/_mainLayout/rooms/$roomId/"
      ]
    },
    "/_authLayout/login": {
      "filePath": "_authLayout/login.tsx",
      "parent": "/_authLayout"
    },
    "/_authLayout/register": {
      "filePath": "_authLayout/register.tsx",
      "parent": "/_authLayout"
    },
    "/_mainLayout/": {
      "filePath": "_mainLayout/index.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/events/create": {
      "filePath": "_mainLayout/events/create.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/inspections/create": {
      "filePath": "_mainLayout/inspections/create.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/admin/": {
      "filePath": "_mainLayout/admin/index.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/events/": {
      "filePath": "_mainLayout/events/index.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/inspections/": {
      "filePath": "_mainLayout/inspections/index.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/profile/": {
      "filePath": "_mainLayout/profile/index.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/room-dashboard/": {
      "filePath": "_mainLayout/room-dashboard/index.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/events/$eventId/edit": {
      "filePath": "_mainLayout/events/$eventId.edit.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/events/$eventId/invite": {
      "filePath": "_mainLayout/events/$eventId.invite.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/rooms/$roomId/edit": {
      "filePath": "_mainLayout/rooms/$roomId.edit.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/events/$eventId/": {
      "filePath": "_mainLayout/events/$eventId.index.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/inspections/$inspectionId/": {
      "filePath": "_mainLayout/inspections/$inspectionId.index.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/profile/$profileId/": {
      "filePath": "_mainLayout/profile/$profileId.index.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/rooms/$roomId/": {
      "filePath": "_mainLayout/rooms/$roomId.index.tsx",
      "parent": "/_mainLayout"
    }
  }
}
ROUTE_MANIFEST_END */
