version: "3.8"

services:
  shared-db:
    image: postgres:13
    container_name: shared_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: auth_db,events_db # Список БД для створення
    ports:
      - "5432:5432"
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - shared_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - shared-db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # AMQP порт
      - "15672:15672" # Management UI порт
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    depends_on:
      - shared-db

volumes:
  shared_postgres_data:
  rabbitmq_data:
