services:
  postgres:
    cpus: 1.0
    mem_limit: 1g

  event-service:
    # scale: 1
    # cpus: 1.0
    # mem_limit: 2g
    # scale: 5
    # cpus: 0.2
    # mem_limit: 256mb
    # scale: 2
    # cpus: 0.5
    # mem_limit: 1gb
    scale: 2
    cpus: 1.0
    mem_limit: 2gb

  api-gateway:
    cpus: 0.5
    mem_limit: 512m
