using Events.API.Entities;

using Microsoft.EntityFrameworkCore;

namespace Events.API.Database
{
    public static class RuntimeSeedData
    {
        private const int TargetEventCount = 500;

        private static readonly Guid AdminUserId = new Guid("11111111-1111-1111-1111-111111111111");

        private static readonly Guid RegularUserId = new Guid("22222222-2222-2222-2222-222222222222");

        private static readonly Guid MaintenanceStaffId = new Guid("33333333-3333-3333-3333-333333333333");

        private static readonly Guid AlphaBuildingId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee");

        private static readonly Guid BetaBuildingId = new Guid("bbbbbbbb-cccc-dddd-eeee-ffffffffffff");

        private static readonly Guid StudyRoomId = new Guid("cccccccc-dddd-eeee-ffff-aaaaaaaaaaaa");

        private static readonly Guid LaundryRoomId = new Guid("eeeeeeee-ffff-aaaa-bbbb-cccccccccccc");

        private static readonly Guid CommonRoomId = new Guid("dddddddd-eeee-ffff-aaaa-bbbbbbbbbbbb");

        private static readonly Guid StudyRoom2Id = new Guid("cccccccc-dddd-eeee-ffff-bbbbbbbbbbbb");

        private static readonly Guid CommonRoom2Id = new Guid("dddddddd-eeee-ffff-aaaa-cccccccccccc");

        private static readonly Guid[] UserIds =
        [
            AdminUserId,
            RegularUserId,
            MaintenanceStaffId,
        ];

        private static readonly (Guid BuildingId, Guid? RoomId, string Location)[] Locations =
        [
            (AlphaBuildingId, null, "Main Hall - Alpha Building"),
            (AlphaBuildingId, StudyRoomId, "Study Room A - Alpha Building"),
            (AlphaBuildingId, StudyRoom2Id, "Study Room B - Alpha Building"),
            (AlphaBuildingId, LaundryRoomId, "Laundry Room - Alpha Building"),
            (BetaBuildingId, CommonRoomId, "Common Room - Beta Building"),
            (BetaBuildingId, CommonRoom2Id, "Common Room 2 - Beta Building"),
            (BetaBuildingId, null, "Main Dining Hall - Beta Building"),
        ];

        private static readonly string[] EventThemes =
        [
            "Community Meetup",
            "Study Session",
            "Movie Night",
            "Workshop",
            "Game Night",
            "Career Talk",
            "Fitness Meetup",
            "Cooking Club",
            "Language Exchange",
            "Hackathon Prep",
        ];

        public static async Task SeedAsync(EventsDbContext context, ILogger logger, CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(context);
            ArgumentNullException.ThrowIfNull(logger);

            var existingCount = await context.Events.CountAsync(cancellationToken);
            if (existingCount >= TargetEventCount)
            {
                logger.LogInformation("Runtime event seeding skipped. Existing events: {ExistingCount}", existingCount);
                return;
            }

            var eventsToCreate = TargetEventCount - existingCount;
            var baseDate = new DateTime(2026, 1, 1, 18, 0, 0, DateTimeKind.Utc);
            var generatedEvents = new List<DormEvent>(eventsToCreate);
            var generatedParticipants = new List<EventParticipant>(eventsToCreate);

            for (var i = 0; i < eventsToCreate; i++)
            {
                var ownerId = UserIds[i % UserIds.Length];
                var location = Locations[i % Locations.Length];
                var eventId = Guid.NewGuid();
                var eventIndex = existingCount + i + 1;

                generatedEvents.Add(new DormEvent
                {
                    Id = eventId,
                    Name = $"{EventThemes[i % EventThemes.Length]} #{eventIndex}",
                    Date = baseDate.AddHours(i * 6),
                    Location = location.Location,
                    Description = $"Autogenerated performance-test event #{eventIndex} for the dorm events catalog.",
                    NumberOfAttendees = 10 + (i % 91),
                    OwnerId = ownerId,
                    IsPublic = i % 4 != 0,
                    BuildingId = location.BuildingId,
                    RoomId = location.RoomId,
                });

                var participantIds = UserIds.Where(userId => userId != ownerId).Take(i % 3).ToArray();
                for (var participantIndex = 0; participantIndex < participantIds.Length; participantIndex++)
                {
                    generatedParticipants.Add(new EventParticipant
                    {
                        Id = Guid.NewGuid(),
                        EventId = eventId,
                        UserId = participantIds[participantIndex],
                        JoinedAt = baseDate.AddHours((i * 6) - participantIndex - 1),
                    });
                }
            }

            await context.Events.AddRangeAsync(generatedEvents, cancellationToken);
            await context.EventParticipants.AddRangeAsync(generatedParticipants, cancellationToken);
            await context.SaveChangesAsync(cancellationToken);

            logger.LogInformation(
                "Runtime event seeding completed. Added {AddedEvents} events and {AddedParticipants} participants.",
                generatedEvents.Count,
                generatedParticipants.Count);
        }
    }
}
