{
 "title": "Notifications WebSocket vs Polling2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Notification Delivery Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mode) (\n  increase(notifications_delivery_latency_ms_milliseconds_count[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification Delivery P50",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, mode) (\n    rate(notifications_delivery_latency_ms_milliseconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification Delivery P90",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 7, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, mode) (\n    rate(notifications_delivery_latency_ms_milliseconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification Delivery P99",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 7, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, mode) (\n    rate(notifications_delivery_latency_ms_milliseconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}