// <auto-generated />
using System;
using Events.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Events.API.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20260505195040_AddEventComments")]
    partial class AddEventComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Events.API.Entities.DormEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfAttendees")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BuildingId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Date = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Welcome party for new dorm residents. Come meet your neighbors and enjoy some refreshments!",
                            IsPublic = true,
                            Location = "Main Hall - Alpha Building",
                            Name = "Welcome Party",
                            NumberOfAttendees = 50,
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BuildingId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Date = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Weekly study group for Computer Science students. Bring your textbooks and questions!",
                            IsPublic = true,
                            Location = "Study Room A - Alpha Building",
                            Name = "Study Group Session",
                            NumberOfAttendees = 15,
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoomId = new Guid("cccccccc-dddd-eeee-ffff-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BuildingId = new Guid("bbbbbbbb-cccc-dddd-eeee-ffffffffffff"),
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Board games, video games, and snacks! A fun evening for all dorm residents.",
                            IsPublic = true,
                            Location = "Common Room - Beta Building",
                            Name = "Game Night",
                            NumberOfAttendees = 25,
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoomId = new Guid("dddddddd-eeee-ffff-aaaa-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            BuildingId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly floor meeting to discuss community guidelines and upcoming events.",
                            IsPublic = false,
                            Location = "2nd Floor Common Area - Alpha Building",
                            Name = "Floor Meeting",
                            NumberOfAttendees = 20,
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            BuildingId = new Guid("bbbbbbbb-cccc-dddd-eeee-ffffffffffff"),
                            Date = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Free pizza night sponsored by the dorm council. First come, first served!",
                            IsPublic = true,
                            Location = "Main Dining Hall - Beta Building",
                            Name = "Pizza Night",
                            NumberOfAttendees = 100,
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BuildingId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Date = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn proper laundry techniques and machine usage. Perfect for first-year students!",
                            IsPublic = true,
                            Location = "Laundry Room - Alpha Building",
                            Name = "Laundry Workshop",
                            NumberOfAttendees = 12,
                            OwnerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoomId = new Guid("eeeeeeee-ffff-aaaa-bbbb-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BuildingId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Date = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advanced mathematics study session. Calculus and statistics focus.",
                            IsPublic = true,
                            Location = "Study Room B - Alpha Building",
                            Name = "Study Session - Advanced Math",
                            NumberOfAttendees = 8,
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoomId = new Guid("cccccccc-dddd-eeee-ffff-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BuildingId = new Guid("bbbbbbbb-cccc-dddd-eeee-ffffffffffff"),
                            Date = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Weekly movie night featuring classic films. Popcorn provided!",
                            IsPublic = true,
                            Location = "Common Room 2 - Beta Building",
                            Name = "Movie Night",
                            NumberOfAttendees = 30,
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoomId = new Guid("dddddddd-eeee-ffff-aaaa-cccccccccccc")
                        });
                });

            modelBuilder.Entity("Events.API.Entities.EventComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "CreatedAt");

                    b.ToTable("EventComments");
                });

            modelBuilder.Entity("Events.API.Entities.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventParticipants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            EventId = new Guid("22222222-2222-2222-2222-222222222222"),
                            JoinedAt = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            EventId = new Guid("22222222-2222-2222-2222-222222222222"),
                            JoinedAt = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-cccccccccccc"),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            JoinedAt = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("44444444-dddd-dddd-dddd-dddddddddddd"),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            JoinedAt = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("55555555-eeee-eeee-eeee-eeeeeeeeeeee"),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            JoinedAt = new DateTime(2023, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("66666666-ffff-ffff-ffff-ffffffffffff"),
                            EventId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            JoinedAt = new DateTime(2023, 12, 31, 18, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("77777777-aaaa-bbbb-cccc-dddddddddddd"),
                            EventId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            JoinedAt = new DateTime(2023, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("88888888-aaaa-bbbb-cccc-dddddddddddd"),
                            EventId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            JoinedAt = new DateTime(2023, 12, 31, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("99999999-aaaa-bbbb-cccc-dddddddddddd"),
                            EventId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            JoinedAt = new DateTime(2023, 12, 31, 20, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("Events.API.Entities.InvitationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("InvitationTokens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            CreatedAt = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ExpiresAt = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Token = "WELCOME2024"
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            CreatedAt = new DateTime(2023, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ExpiresAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Token = "STUDY2024"
                        },
                        new
                        {
                            Id = new Guid("30303030-3030-3030-3030-303030303030"),
                            CreatedAt = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ExpiresAt = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Token = "GAME2024"
                        },
                        new
                        {
                            Id = new Guid("40404040-4040-4040-4040-404040404040"),
                            CreatedAt = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ExpiresAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Token = "LAUNDRY2024"
                        },
                        new
                        {
                            Id = new Guid("50505050-5050-5050-5050-505050505050"),
                            CreatedAt = new DateTime(2023, 12, 31, 18, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ExpiresAt = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Token = "MATH2024"
                        },
                        new
                        {
                            Id = new Guid("60606060-6060-6060-6060-606060606060"),
                            CreatedAt = new DateTime(2023, 12, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            ExpiresAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Token = "MOVIE2024"
                        });
                });

            modelBuilder.Entity("Events.API.Entities.EventComment", b =>
                {
                    b.HasOne("Events.API.Entities.DormEvent", "Event")
                        .WithMany("Comments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Events.API.Entities.EventParticipant", b =>
                {
                    b.HasOne("Events.API.Entities.DormEvent", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Events.API.Entities.InvitationToken", b =>
                {
                    b.HasOne("Events.API.Entities.DormEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Events.API.Entities.DormEvent", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
